export const lessons = [
  {
    id: "agent-loop",
    number: "01",
    title: "认识 Hermes",
    shortTitle: "从任务到行动",
    duration: "8 分钟",
    summary: "建立 Agent 回合的心智模型：理解意图、选择工具、请求授权、执行并沉淀经验。",
    objective: "识别一次完整 Agent 回合，并为有副作用的动作选择合适授权范围。",
    command: "hermes --tui",
    trace: ["读取用户任务与当前上下文", "选择 terminal 与 file 工具", "检测到写入副作用", "暂停并请求授权"],
    steps: [
      { title: "它不只生成文本", body: "Hermes 的核心是工具调用循环。模型负责推理，运行时负责工具注册、权限、会话与结果回传。" },
      { title: "行动必须可观察", body: "TUI 会把思考、工具进度、审批与最终回答分开呈现。你应关注它做了什么，而不只看最后一句话。" },
      { title: "授权要匹配风险", body: "读取通常风险较低；写文件、执行命令或发消息会产生副作用，应缩小范围并保留撤销路径。" },
    ],
    checkpoints: ["识别任务意图", "找到适合的工具", "选择审批范围", "解释执行结果"],
    practice: {
      type: "choice",
      prompt: "Hermes 要整理 Markdown 文件，并在当前目录写入摘要。你第一次运行这个任务，应该如何授权？",
      options: [
        { id: "once", label: "仅允许这一次", detail: "只覆盖本次写入，完成后自动失效。" },
        { id: "session", label: "本会话始终允许", detail: "之后同类写入不再询问。" },
        { id: "always", label: "永久允许", detail: "未来所有会话都跳过同类确认。" },
        { id: "deny", label: "拒绝", detail: "任务只能停在只读分析。" },
      ],
      correct: "once",
      success: "正确。首次执行带写入的任务时，单次授权兼顾效率与最小权限。",
      hint: "先考虑最小可行授权，而不是最方便的授权。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart",
  },
  {
    id: "model-profile",
    number: "02",
    title: "模型与身份",
    shortTitle: "配置可替换的大脑",
    duration: "10 分钟",
    summary: "理解 provider、model、profile 与 SOUL 的边界，避免把模型能力和 Agent 身份混在一起。",
    objective: "为一个本地研究助手选择模型与隔离配置，并生成可复现的设置命令。",
    command: "hermes model",
    trace: ["选择 provider 与 model", "校验至少 64K 上下文", "写入非密钥配置", "切换独立 profile"],
    steps: [
      { title: "模型可以随时替换", body: "Hermes 支持 Nous Portal、OpenRouter、OpenAI、Anthropic 与兼容端点。切换模型不要求修改业务代码。" },
      { title: "Profile 隔离运行环境", body: "不同 profile 可以拥有独立模型、Skills、MCP 与消息网关，适合把研究、编码和个人助理分开。" },
      { title: "SOUL 描述行为风格", body: "模型决定基础能力，SOUL.md 描述长期个性与原则。不要把密钥或临时任务写入人格文件。" },
    ],
    checkpoints: ["区分 provider 与 model", "理解 profile 隔离", "避免明文保存密钥", "生成配置命令"],
    practice: {
      type: "builder",
      prompt: "为“本地研究助手”建立一套配置。完成两个选择后运行检查。",
      fields: [
        { id: "provider", label: "模型来源", type: "select", options: ["Nous Portal", "OpenRouter", "本地 Ollama"] },
        { id: "profile", label: "Profile", type: "select", options: ["research", "default", "personal"] },
      ],
      commandTemplate: ({ provider, profile }) => `hermes -p ${profile || "<profile>"} model  # ${provider || "<provider>"}`,
      success: "配置边界清晰：模型来源可替换，研究环境与默认环境相互隔离。",
      hint: "两个字段都需要明确选择。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/configuring-models",
  },
  {
    id: "tools-approval",
    number: "03",
    title: "工具与审批",
    shortTitle: "组合最小工具链",
    duration: "12 分钟",
    summary: "从任务反推最少工具集，理解 terminal、file、browser、code execution 的能力与风险。",
    objective: "为代码库盘点任务选择必要工具，并加入副作用审批。",
    command: "hermes tools",
    trace: ["读取仓库结构", "执行只读搜索", "生成变更建议", "写入前触发 approval"],
    steps: [
      { title: "工具不是越多越好", body: "工具越多，选择成本和攻击面越大。Blank Slate 模式默认只保留最低限度的 File 与 Terminal。" },
      { title: "读写能力分开思考", body: "先让 Agent 用只读工具形成计划，再开放写入。这样更容易审查范围和发现错误假设。" },
      { title: "结果要能验证", body: "命令成功并不等于任务正确。要求 Agent 汇报变更、测试与剩余风险。" },
    ],
    checkpoints: ["识别只读工具", "限制工具范围", "加入写入审批", "要求验证证据"],
    practice: {
      type: "multi",
      prompt: "选择完成“扫描当前仓库并生成 README 草稿”所需的最小能力集合。",
      options: [
        { id: "terminal", label: "Terminal", detail: "列出目录并搜索内容" },
        { id: "file", label: "File", detail: "读取文件并写入草稿" },
        { id: "approval", label: "Write approval", detail: "写入前暂停确认" },
        { id: "browser", label: "Browser", detail: "控制浏览器页面" },
        { id: "image", label: "Image generation", detail: "生成位图资产" },
      ],
      correct: ["terminal", "file", "approval"],
      success: "工具链足够完成任务，且写入动作仍处于你的控制之下。",
      hint: "这个任务不需要访问网页或生成图片。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools",
  },
  {
    id: "sessions-memory",
    number: "04",
    title: "会话与记忆",
    shortTitle: "让经验跨会话复用",
    duration: "11 分钟",
    summary: "区分当前上下文、session_search、Agent memory 与 user profile，避免过度记忆。",
    objective: "判断信息应留在会话历史、Agent 笔记还是用户档案中。",
    command: "hermes sessions list",
    trace: ["搜索过去会话", "提取相关片段", "判断是否值得长期保存", "通过 memory gate 写入"],
    steps: [
      { title: "Session 是事实记录", body: "会话保存原始交互，FTS5 搜索适合找回过去发生过什么，而不是把所有内容都塞入当前提示。" },
      { title: "Memory 是压缩后的经验", body: "Agent memory 适合保存可复用流程、项目约定与踩坑结论；user profile 适合稳定偏好与身份事实。" },
      { title: "记忆也需要审批", body: "长期写入会改变后续行为。开启 write approval 后，可以查看、批准或拒绝待写入内容。" },
    ],
    checkpoints: ["区分会话与记忆", "选择正确目标", "跳过短期信息", "审查长期写入"],
    practice: {
      type: "choice",
      prompt: "你想找回“上周某次调试中出现的完整报错和当时命令”，应该先用什么？",
      options: [
        { id: "session-search", label: "session_search", detail: "检索原始会话与工具上下文" },
        { id: "memory", label: "Agent memory", detail: "读取压缩后的长期经验" },
        { id: "user", label: "User profile", detail: "读取稳定个人偏好" },
        { id: "soul", label: "SOUL.md", detail: "读取 Agent 人格原则" },
      ],
      correct: "session-search",
      success: "正确。完整历史细节属于会话检索；总结后的复用结论才适合进入 memory。",
      hint: "你需要的是过去一次交互的原始细节。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/features/memory",
  },
  {
    id: "skills-mcp",
    number: "05",
    title: "Skills 与 MCP",
    shortTitle: "扩展知识与外部工具",
    duration: "14 分钟",
    summary: "理解 Skill 是渐进披露的操作知识，MCP 是外部工具协议，两者解决不同问题。",
    objective: "组装一个可维护的 SKILL.md 骨架，并识别何时应该接入 MCP。",
    command: "hermes skills browse",
    trace: ["匹配 Skill 描述", "按需读取 SKILL.md", "连接 MCP 并发现工具", "按白名单暴露能力"],
    steps: [
      { title: "Skill 教 Agent 怎么做", body: "Skill 用 Markdown 描述触发条件、步骤、陷阱与验证。只有匹配任务时才加载完整内容。" },
      { title: "MCP 给 Agent 新工具", body: "MCP 连接 stdio 或 HTTP 工具服务器。它提供能力，不自动提供你团队的操作规范。" },
      { title: "安装前先审查", body: "Skills Hub 会做安全扫描；MCP 应限制服务器、环境变量和工具白名单，尤其要过滤破坏性操作。" },
    ],
    checkpoints: ["理解渐进披露", "区分知识与能力", "补全验证章节", "限制 MCP 暴露面"],
    practice: {
      type: "multi",
      prompt: "选择一份可执行 SKILL.md 最关键的四个组成部分。",
      options: [
        { id: "frontmatter", label: "Frontmatter", detail: "名称与触发描述" },
        { id: "when", label: "When to Use", detail: "适用边界" },
        { id: "procedure", label: "Procedure", detail: "可操作步骤" },
        { id: "verification", label: "Verification", detail: "完成证据" },
        { id: "slogan", label: "宣传口号", detail: "营销式一句话" },
      ],
      correct: ["frontmatter", "when", "procedure", "verification"],
      success: "结构完整。好的 Skill 明确何时用、如何做，以及怎样证明已经做对。",
      hint: "优先选择能约束触发、执行和验收的内容。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/features/skills",
  },
  {
    id: "gateway-cron",
    number: "06",
    title: "消息与自动化",
    shortTitle: "让 Hermes 按时送达",
    duration: "12 分钟",
    summary: "用 Gateway 统一消息入口，用 Cron 在离线时执行，并把结果送回指定平台。",
    objective: "构建一个工作日早报任务，明确时间、任务与交付目的地。",
    command: "hermes gateway setup",
    trace: ["Gateway 接收消息", "Cron 在设定时间唤醒", "Agent 执行任务", "结果路由到指定平台"],
    steps: [
      { title: "Gateway 是常驻入口", body: "一个进程可以连接 Telegram、Discord、Slack、WhatsApp 等平台，并保持跨平台会话连续性。" },
      { title: "Cron 保存执行意图", body: "任务由 schedule、prompt、可选 skills、工作目录和 delivery 组成。先让普通对话跑通，再加定时执行。" },
      { title: "交付失败也要可追踪", body: "自动化应保留执行历史、失败状态与重试路径，不要把“定时触发”误当作“成功送达”。" },
    ],
    checkpoints: ["区分 Gateway 与 Cron", "写出稳定任务", "设置交付目标", "保留运行历史"],
    practice: {
      type: "builder",
      prompt: "创建一个工作日 09:00 的项目早报，并发送到 Telegram。",
      fields: [
        { id: "schedule", label: "Schedule", type: "select", options: ["weekdays at 09:00", "every 5m", "every 1d at 23:00"] },
        { id: "delivery", label: "Delivery", type: "select", options: ["Telegram", "CLI only", "Discord"] },
        { id: "task", label: "Task", type: "text", placeholder: "汇总项目状态、阻塞项和今日计划" },
      ],
      expected: { schedule: "weekdays at 09:00", delivery: "Telegram" },
      commandTemplate: ({ schedule, delivery, task }) => `hermes cron create "${schedule || "<schedule>"}" "${task || "<task>"}"  # deliver: ${delivery || "<target>"}`,
      success: "早报任务具备明确时间、可验证内容和交付目标。",
      hint: "题目指定了工作日 09:00 和 Telegram。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/features/cron",
  },
  {
    id: "delegation",
    number: "07",
    title: "委派与并行",
    shortTitle: "拆分独立工作流",
    duration: "13 分钟",
    summary: "把互不依赖的子任务交给隔离 subagents，并提供足够上下文、边界与返回格式。",
    objective: "识别可并行任务，并避免把模糊代词或共享写入交给子任务。",
    command: "/agents",
    trace: ["拆分独立任务", "为每个任务补全上下文", "并行启动 subagents", "主 Agent 汇总与验证"],
    steps: [
      { title: "并行需要独立性", body: "研究、测试审查、文档核对可以并行；多个 Agent 同时修改同一文件通常不适合。" },
      { title: "上下文必须自包含", body: "子 Agent 不知道“那个错误”指什么。任务要包含目标、输入、约束、文件范围与期望输出。" },
      { title: "主 Agent 负责收口", body: "委派不是甩出责任。主 Agent 仍需检查冲突、合并证据并向用户报告剩余风险。" },
    ],
    checkpoints: ["判断任务独立性", "补齐子任务上下文", "并行运行", "集中验证结果"],
    practice: {
      type: "multi",
      prompt: "为发布前检查选择可以并行委派的三条独立工作流。",
      options: [
        { id: "research", label: "依赖与安全公告", detail: "只读外部研究" },
        { id: "tests", label: "测试失败归类", detail: "分析现有测试输出" },
        { id: "docs", label: "文档链接核对", detail: "检查链接与示例" },
        { id: "same-file-a", label: "修改 App.jsx 上半段", detail: "写入共享文件" },
        { id: "same-file-b", label: "修改 App.jsx 下半段", detail: "写入同一共享文件" },
      ],
      correct: ["research", "tests", "docs"],
      success: "拆分合理。这三项输入和写入边界独立，适合并行后统一汇总。",
      hint: "避免让两个子任务同时写同一个文件。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/features/delegation",
  },
  {
    id: "final-challenge",
    number: "08",
    title: "安全毕业挑战",
    shortTitle: "设计一个可控工作流",
    duration: "15 分钟",
    summary: "把范围、审批、可恢复性和证据组合成一个可长期运行的 Hermes 工作流。",
    objective: "审查自动 PR 助手方案，选出生产化前不可缺少的安全控制。",
    command: "hermes checkpoints list",
    trace: ["限定仓库与分支", "写入前审批", "创建 checkpoint", "测试并报告证据"],
    steps: [
      { title: "先限定作用域", body: "明确仓库、分支、文件与外部系统。边界模糊时，Agent 应暂停澄清，而不是自行扩大范围。" },
      { title: "为副作用保留恢复点", body: "文件写入前创建 checkpoint，配合 /rollback 或 Git 变更，让失败可以恢复。" },
      { title: "用证据完成交付", body: "最终报告应包含实际变更、测试结果、未覆盖状态与需要人工决策的部分。" },
    ],
    checkpoints: ["限定执行范围", "设置审批门", "保留回滚路径", "输出验证证据"],
    practice: {
      type: "multi",
      prompt: "一个定时 PR 审查 Agent 可以读代码、写建议并发送 Slack。上线前必须具备哪些控制？",
      options: [
        { id: "scope", label: "仓库与分支白名单", detail: "限制可访问目标" },
        { id: "approval", label: "写入与发送审批", detail: "控制外部副作用" },
        { id: "rollback", label: "Checkpoint / Git 恢复点", detail: "支持失败恢复" },
        { id: "report", label: "测试与交付证据", detail: "证明结果并暴露风险" },
        { id: "yolo", label: "永久跳过确认", detail: "提高无人值守速度" },
      ],
      correct: ["scope", "approval", "rollback", "report"],
      success: "毕业挑战完成。你已经把 Agent 能力放进可审查、可恢复、可验证的运行边界。",
      hint: "自动化越长期，边界、恢复和证据越重要。",
    },
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/checkpoints-and-rollback",
  },
];

export const repositories = [
  {
    name: "NousResearch/hermes-agent",
    role: "官方核心",
    language: "Python + TypeScript",
    url: "https://github.com/NousResearch/hermes-agent",
    idea: "把模型、工具运行时、持久记忆、Skills、消息网关与自动化组合成一个会持续学习的 Agent。",
    design: "provider 可替换、运行界面与核心解耦、工具按能力注册、会话与长期记忆分层、写入与网络动作设审批门。",
    features: ["TUI / CLI / Desktop", "Memory 与 session search", "Skills / MCP / Plugins", "Cron / Gateway / Delegation"],
  },
  {
    name: "fathah/hermes-desktop",
    role: "社区桌面端",
    language: "TypeScript",
    url: "https://github.com/fathah/hermes-desktop",
    idea: "用原生桌面工作台降低安装、provider 配置和日常管理门槛。",
    design: "本地或远程 Hermes 后端 + SSE 流式界面，围绕会话、Profile、Memory、Skills、Schedules 与 Gateway 组织功能。",
    features: ["引导式首次安装", "流式聊天与工具进度", "Profile / Memory / Soul", "Schedules 与 Messaging"],
  },
  {
    name: "nesquena/hermes-webui",
    role: "社区 Web UI",
    language: "Python + Vanilla JS",
    url: "https://github.com/nesquena/hermes-webui",
    idea: "用轻量浏览器界面提供接近 CLI 的能力，并可通过 SSH tunnel 在多设备访问。",
    design: "左侧会话、中部聊天、右侧工作区三栏；强调零构建依赖、移动端与现有 Hermes 配置复用。",
    features: ["三栏工作区", "会话与文件浏览", "Profile / workspace 控制", "移动端与安全隧道"],
  },
  {
    name: "outsourc-e/hermes-workspace",
    role: "社区工作区",
    language: "JavaScript",
    url: "https://github.com/outsourc-e/hermes-workspace",
    idea: "把聊天、终端、记忆、Skills 与检查器收敛到一个原生 Web workspace。",
    design: "以操作面板而不是单一聊天框承载 Agent 的多种状态，突出过程可见性。",
    features: ["Chat + Terminal", "Memory / Skills", "运行检查器", "本地工作区"],
  },
  {
    name: "NousResearch/hermes-agent-self-evolution",
    role: "官方实验项目",
    language: "Python",
    url: "https://github.com/NousResearch/hermes-agent-self-evolution",
    idea: "用 DSPy + GEPA 对 Skills、提示与代码进行基于评测的迭代优化。",
    design: "把“自我改进”从直觉编辑变成候选生成、评测、比较与保留优胜版本的闭环。",
    features: ["GEPA 优化", "Skill 演化", "可度量评测", "实验追踪"],
  },
  {
    name: "0xNyk/awesome-hermes-agent",
    role: "社区资源索引",
    language: "Markdown",
    url: "https://github.com/0xNyk/awesome-hermes-agent",
    idea: "按 surfaces、skills、plugins、memory providers 与 guides 聚合生态资源。",
    design: "用成熟度标签与类别帮助用户区分 production、beta 与 experimental 项目。",
    features: ["Skills 索引", "Plugins 索引", "Memory providers", "教程与部署资源"],
  },
  {
    name: "alchaincyf/hermes-agent-orange-book",
    role: "中文学习资料",
    language: "PDF / Markdown",
    url: "https://github.com/alchaincyf/hermes-agent-orange-book",
    idea: "用六部分、二十一节串联自改进、记忆、工具、平台、多 Agent、安全与部署。",
    design: "以概念解释配合界面与架构分析，适合在官方文档之外建立整体心智模型。",
    features: ["中文完整指南", "三层记忆分析", "多 Agent / Kanban", "安全边界"],
  },
  {
    name: "Yonkoo11/hermes-dojo",
    role: "示例 Skill",
    language: "Python",
    url: "https://github.com/Yonkoo11/hermes-dojo",
    idea: "从 session 日志发现失败模式，定位弱 Skills，自动修复并再次测量。",
    design: "measure → identify weakness → evolve → measure again → report，展示闭环学习如何落到一个具体 Skill。",
    features: ["失败模式检测", "弱点排序", "Skill 修复", "学习曲线报告"],
  },
];

export const architectureLayers = [
  { title: "Content", detail: "课程、任务、官方来源与项目分析全部由结构化数据驱动。" },
  { title: "Learning Engine", detail: "练习判定、反馈、掌握度与课程解锁保持为纯前端状态机。" },
  { title: "Persistence", detail: "版本化 localStorage 保存完成课程与最近位置，不采集账号数据。" },
  { title: "UI Shell", detail: "React + Vite 三栏工作台，使用 Lucide 图标和响应式布局。" },
];
