export const phases = [
  { id: "foundation", number: "I", title: "启动与基础", level: "Beginner" },
  { id: "reliable", number: "II", title: "可靠交互", level: "Beginner → Intermediate" },
  { id: "extensions", number: "III", title: "扩展与自动化", level: "Intermediate" },
  { id: "production", number: "IV", title: "工程化与进阶", level: "Advanced" },
];

const option = (id, label, detail) => ({ id, label, detail });

export const onboardingTracks = [
  {
    id: "desktop",
    label: "桌面应用",
    title: "下载 Hermes Desktop",
    summary: "适合第一次使用 Hermes 的学习者。安装器会配置桌面应用与 CLI，两者共享配置、会话和 Skills。",
    recommended: true,
    steps: [
      { title: "打开官方下载页", body: "在 macOS 或 Windows 下载对应的 Hermes Desktop 安装器。", action: "打开下载页", url: "https://hermes-agent.nousresearch.com/" },
      { title: "运行安装器", body: "按向导完成依赖与 Hermes 核心安装；Windows 无需管理员权限。" },
      { title: "完成首次设置", body: "选择 Provider 和模型，先完成一次普通聊天，再启用外部平台。", command: "hermes setup" },
      { title: "已有 CLI 时启动桌面端", body: "桌面端会复用现有配置、密钥、会话与 Skills。", command: "hermes desktop" },
    ],
    verify: "桌面端能创建新会话、选择模型并收到一条普通回复。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/desktop",
  },
  {
    id: "mac",
    label: "macOS 终端",
    title: "在 macOS 安装 Hermes CLI",
    summary: "只需预先安装 Git；官方安装器会管理 uv、Python 3.11、Node.js 22、ripgrep 与 ffmpeg。",
    steps: [
      { title: "检查 Git", body: "如果命令不可用，先安装 Xcode Command Line Tools。", command: "git --version" },
      { title: "运行官方安装器", body: "在 Terminal 中执行一行安装命令。", command: "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash" },
      { title: "刷新终端环境", body: "新开终端，或在当前 zsh 会话重新加载 PATH。", command: "source ~/.zshrc" },
      { title: "配置并验收", body: "完成 Setup 后先运行 Doctor，再开始普通聊天。", command: "hermes setup && hermes doctor && hermes" },
    ],
    verify: "hermes doctor 无阻断错误，hermes 能进入聊天界面。",
    docs: "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
  },
  {
    id: "windows",
    label: "Windows 原生",
    title: "在 Windows 原生安装 Hermes",
    summary: "适合希望直接在 PowerShell、Windows Terminal 或桌面应用中运行 Hermes 的用户。",
    steps: [
      { title: "打开 PowerShell", body: "使用普通用户权限即可，无需以管理员身份运行。" },
      { title: "运行官方安装脚本", body: "安装位置默认为 %LOCALAPPDATA%\\hermes，并写入用户 PATH。", command: "iex (irm https://hermes-agent.nousresearch.com/install.ps1)" },
      { title: "重新打开终端", body: "安装结束后新开 PowerShell，让用户 PATH 生效。" },
      { title: "检查并启动", body: "完成配置检查；需要 GUI 时从同一安装启动桌面端。", command: "hermes doctor\nhermes desktop" },
    ],
    verify: "新终端能识别 hermes，桌面端与 CLI 能看到同一套会话。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-native",
  },
  {
    id: "wsl",
    label: "Windows WSL2",
    title: "通过 WSL2 使用 Linux 版 Hermes",
    summary: "适合偏好 Linux 工具链、systemd 和本地开发环境的 Windows 用户；官方建议 Ubuntu LTS。",
    steps: [
      { title: "安装 WSL2", body: "在管理员 PowerShell 执行并按提示重启。", command: "wsl --install" },
      { title: "确认使用 WSL2", body: "目标发行版的 VERSION 应为 2，而不是 1。", command: "wsl --list --verbose" },
      { title: "在 Ubuntu 内安装", body: "打开 WSL2 终端后使用 Linux/macOS 安装器。", command: "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash" },
      { title: "刷新并运行", body: "项目建议放在 ~/code，而不是 /mnt/c，以减少跨文件系统开销。", command: "source ~/.bashrc && hermes" },
    ],
    verify: "WSL 发行版显示 VERSION 2，Hermes 能在 Linux 文件系统中的项目目录正常聊天。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-wsl-quickstart",
  },
  {
    id: "feishu",
    label: "连接飞书",
    title: "把 Hermes 接入飞书群聊和私聊",
    summary: "推荐使用 WebSocket 长连接：Hermes 主动向飞书建立连接，不需要公网 URL。",
    steps: [
      { title: "启动接入向导", body: "选择 Feishu / Lark。推荐用飞书手机扫描二维码自动创建应用并保存凭据。", command: "hermes gateway setup" },
      { title: "手动模式准备应用", body: "在飞书开放平台创建企业自建应用，启用机器人，保存 App ID 与 App Secret。", action: "打开飞书应用控制台", url: "https://open.feishu.cn/app" },
      { title: "配置权限和事件", body: "至少添加 im:message、im:message:send_as_bot、im:resource、im:chat、im:chat:readonly，并订阅 im.message.receive_v1。" },
      { title: "发布并启动 Gateway", body: "发布应用版本并等待管理员审批；然后启动 Gateway，在群聊中 @机器人做冒烟测试。", command: "hermes gateway" },
    ],
    verify: "群聊中 @Hermes 后能收到回复；生产环境已配置 FEISHU_ALLOWED_USERS。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu",
  },
];

export const lessons = [
  {
    id: "installation-channels", number: "00", phaseId: "foundation", level: "Beginner", title: "下载与多端接入", shortTitle: "安装 Hermes，并完成桌面与飞书首轮体验",
    summary: "根据设备选择桌面安装器或终端安装，完成首次配置，再把同一个 Hermes 安全地连接到飞书。",
    objective: "能够选择正确安装路径，完成 Doctor 验收，并解释桌面端与飞书端如何共享 Hermes 运行时。",
    prerequisites: ["macOS 或 Windows 设备", "可访问官方安装页", "一个模型 Provider"],
    preQuiz: { prompt: "第一次接触 Hermes，官方推荐哪种安装路径？", options: [option("desktop", "Hermes Desktop 安装器", "同时安装桌面应用与 CLI"), option("source", "直接从源码构建", "更适合贡献者"), option("docker", "先搭建生产容器", "不适合作为首次体验")], correct: "desktop", explanation: "macOS/Windows 首次使用推荐桌面安装器；熟悉终端后也可以选择 CLI-only 安装。" },
    command: "hermes gateway setup",
    trace: ["选择设备与安装方式", "完成 Setup 和 Doctor", "在桌面端执行一次任务", "连接飞书并验证 @提及"],
    steps: [
      { title: "先选安装入口", body: "macOS/Windows 初学者优先使用 Desktop 安装器；CLI 用户选择 macOS shell、Windows 原生 PowerShell 或 WSL2。" },
      { title: "先验收再扩展", body: "安装后运行 Setup、Doctor 和一次普通聊天。只有基础会话通过后，才继续配置桌面工作流或飞书 Gateway。" },
      { title: "桌面端共享运行时", body: "hermes desktop 会复用当前配置、密钥、Sessions 与 Skills。桌面端是操作界面，不是另一套独立 Agent。" },
      { title: "飞书走 Gateway", body: "推荐 WebSocket 长连接，不需要公网地址。群聊默认要求 @机器人；生产使用必须限制用户和群组范围。" },
    ],
    checkpoints: ["选择安装路径", "完成 Doctor 验收", "完成桌面模拟", "完成飞书模拟"],
    lab: { task: "完成一个从安装到飞书消息的端到端冒烟测试。", input: "一台 macOS/Windows 设备、可用 Provider、飞书企业自建应用或扫码创建权限。", procedure: ["选择并执行对应安装路径", "运行 Setup、Doctor 和一次普通聊天", "在桌面端完成新会话与单次审批", "运行 gateway setup 并选择 Feishu/Lark", "发布飞书应用并在群聊 @Hermes"], successCriteria: ["CLI 与桌面端共享会话", "Doctor 无阻断错误", "飞书只响应允许用户和有效 @提及", "App Secret 未出现在聊天或截图中"] },
    practice: { type: "choice", prompt: "Hermes 运行在个人电脑且没有公网 URL，连接飞书应该优先选择什么？", options: [option("websocket", "WebSocket 长连接", "出站连接，无需公网入口"), option("webhook", "公开 Webhook", "需要可达 HTTP 地址"), option("poll", "每分钟轮询", "不是官方推荐连接方式")], correct: "websocket", success: "正确。个人电脑或私有服务器优先使用 WebSocket 长连接。", hint: "选择不要求公网 URL、由 Hermes 主动建立的连接方式。" },
    takeaways: ["先建立可工作的本地聊天", "桌面和飞书共享同一个 Hermes 运行时"], troubleshooting: "命令不可用时先刷新 PATH；飞书不回复时检查应用是否已发布、im.message.receive_v1、Gateway 状态、@提及和用户白名单。",
    references: [{ label: "Installation", url: "https://hermes-agent.nousresearch.com/docs/getting-started/installation" }, { label: "Desktop", url: "https://hermes-agent.nousresearch.com/docs/user-guide/desktop" }, { label: "Windows Native", url: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-native" }, { label: "Feishu", url: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu" }],
  },
  {
    id: "setup-doctor", number: "01", phaseId: "foundation", level: "Beginner", title: "环境与诊断", shortTitle: "先建立一个可工作的 Hermes",
    summary: "从安装、Setup 到 Doctor，建立可重复的最小启动路径；先通过一次聊天验收，再逐步添加能力。",
    objective: "完成最小配置，读懂诊断结果，并按正确顺序恢复一个无法对话的 Hermes。",
    prerequisites: ["Python 3.11+", "可访问模型 Provider", "终端基础操作"],
    preQuiz: { prompt: "安装后第一条验收标准应该是什么？", options: [option("chat", "完成一次普通聊天", "证明 Provider、模型和基础运行时可用"), option("cron", "先创建 Cron", "自动化依赖更长的链路"), option("mcp", "先接入 MCP", "会引入额外变量")], correct: "chat", explanation: "先得到一个可工作的聊天基线，后续故障才容易定位。" },
    command: "hermes doctor",
    trace: ["运行 hermes setup", "选择 Quick / Full / Blank Slate", "完成首次聊天", "用 doctor 复核环境"],
    steps: [
      { title: "选择安装模式", body: "Quick Setup 适合首次使用；Full Setup 展开所有选项；Blank Slate 仅保留 Provider、模型、File 与 Terminal，适合从最小能力面开始。" },
      { title: "先验收基础聊天", body: "运行 hermes --tui 并完成一个无需工具的问答。不要在这个基线通过前接入 Gateway、Cron、Skills、MCP 或路由。" },
      { title: "读懂 Doctor", body: "hermes doctor 用于检查配置、凭据和关键依赖。诊断的价值是缩小故障域，而不是把所有配置重新安装一遍。" },
      { title: "按层恢复", body: "建议顺序是 doctor → model → setup → sessions → gateway。每一步只验证一个层级，避免同时改变多个变量。" },
    ],
    checkpoints: ["选择合适 Setup 模式", "完成首次聊天", "运行 Doctor", "按层恢复故障"],
    lab: { task: "为一台新设备制定最小验收流程。", input: "Hermes 已安装，但尚未配置 Provider，也没有启用任何扩展。", procedure: ["运行 hermes setup 并选择 Quick Setup", "配置 Provider 与模型", "进入 TUI 完成一次普通问答", "运行 hermes doctor 记录检查结果"], successCriteria: ["聊天有正常模型响应", "Doctor 无阻断性错误", "未提前启用 Gateway/MCP"] },
    practice: { type: "multi", prompt: "选择合理的首次安装验收顺序。", options: [option("setup", "hermes setup", "生成基础配置"), option("chat", "首次聊天", "验证 Provider 与模型"), option("doctor", "hermes doctor", "检查环境健康"), option("gateway", "Gateway setup", "暂不需要"), option("cron", "Cron create", "暂不需要")], correct: ["setup", "chat", "doctor"], success: "路径正确：先配置、再对话、最后复核健康状态。", hint: "只选择建立最小工作基线所需的三步。" },
    takeaways: ["先让一个聊天回合工作", "一次只改变一个故障变量"], troubleshooting: "若 Doctor 通过但聊天失败，先用 hermes model 检查 Provider、模型名称与凭据，再回到 setup。",
    references: [{ label: "Quickstart", url: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart" }, { label: "Configuration", url: "https://hermes-agent.nousresearch.com/docs/user-guide/configuration" }],
  },
  {
    id: "agent-loop", number: "02", phaseId: "foundation", level: "Beginner", title: "Agent Loop", shortTitle: "从任务到可观察行动",
    summary: "理解意图、计划、工具调用、观察结果与继续迭代组成的 Agent 回合，并为副作用设置审批。",
    objective: "识别一次完整 Agent 回合，为读写动作选择匹配风险的授权范围。",
    prerequisites: ["完成 Lesson 01", "能够进入 Hermes TUI"],
    preQuiz: { prompt: "Hermes 和普通聊天模型最关键的区别是什么？", options: [option("tools", "能在循环中调用工具", "行动结果会返回模型继续判断"), option("long", "回答更长", "长度不是 Agent 的定义"), option("persona", "有固定人格", "SOUL 只是其中一层")], correct: "tools", explanation: "Agent 的核心是可观察、可迭代的工具调用闭环。" },
    command: "hermes --tui",
    trace: ["理解任务与上下文", "选择最小工具", "审批副作用", "观察结果并验证"],
    steps: [
      { title: "模型负责决策", body: "模型根据任务和观察结果决定下一步；运行时负责注册工具、执行、权限、会话和结果回传。" },
      { title: "轨迹比答案重要", body: "TUI 把工具进度、审批与最终回答分开呈现。检查它实际做了什么，而不只看最后一句话。" },
      { title: "授权匹配风险", body: "读取通常风险较低；写文件、执行命令、发消息会产生副作用。首次运行应优先单次、窄范围授权。" },
      { title: "用证据结束回合", body: "命令退出码为零不代表任务正确。要求 Hermes 汇报变更、测试、未覆盖项与恢复方式。" },
    ],
    checkpoints: ["识别 Agent Loop", "选择最小工具", "设置审批范围", "要求验证证据"],
    lab: { task: "让 Hermes 盘点一个 Markdown 目录并生成只读报告。", input: "一个包含 5 个 Markdown 文件的练习目录。", procedure: ["先要求列出文件和计划", "只批准读取与搜索", "审查报告中的文件计数", "需要写摘要时单独批准一次写入"], successCriteria: ["初次分析没有写入", "报告与目录实际文件数一致", "写入授权只覆盖目标摘要"] },
    practice: { type: "choice", prompt: "Hermes 要在当前目录写入摘要，且这是第一次运行。如何授权？", options: [option("once", "仅允许这一次", "完成后自动失效"), option("session", "本会话始终允许", "后续同类写入不再询问"), option("always", "永久允许", "未来会话也跳过确认"), option("deny", "拒绝全部", "任务停在只读阶段")], correct: "once", success: "正确。首次写入使用单次授权，兼顾效率与最小权限。", hint: "选择能完成任务的最小授权。" },
    takeaways: ["Agent 是循环而非单次生成", "副作用需要可观察和可恢复"], troubleshooting: "若工具循环反复执行同一步，暂停并补充成功标准、允许的工具和最大尝试次数。",
    references: [{ label: "CLI", url: "https://hermes-agent.nousresearch.com/docs/user-guide/cli" }, { label: "Tools", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools" }],
  },
  {
    id: "models-profiles", number: "03", phaseId: "foundation", level: "Beginner", title: "模型与 Profile", shortTitle: "配置可替换的大脑与隔离身份",
    summary: "区分 Provider、Model、Profile 与 SOUL，并认识 Nous Hermes 模型谱系及推理/非推理模式。",
    objective: "为研究任务选择模型来源和独立 Profile，同时把密钥与普通配置分离。",
    prerequisites: ["理解基础配置目录", "至少有一个可用 Provider"],
    preQuiz: { prompt: "API 密钥最适合放在哪里？", options: [option("env", "~/.hermes/.env", "用于敏感凭据"), option("yaml", "config.yaml", "适合普通设置"), option("soul", "SOUL.md", "只描述行为原则")], correct: "env", explanation: "秘密写入 .env，普通设置留在 config.yaml。" },
    command: "hermes model",
    trace: ["选择 Provider", "选择模型与上下文", "写入非密钥配置", "切换独立 Profile"],
    steps: [
      { title: "四层不要混淆", body: "Provider 提供推理服务，Model 决定基础能力，Profile 隔离一套 Agent 环境，SOUL.md 描述长期行为风格。" },
      { title: "Profile 隔离任务", body: "研究、编码和个人助理应使用不同 Profile，以隔离模型、Skills、MCP、Memory 和消息入口。" },
      { title: "认识 Hermes 4.3", body: "Hermes-4.3-36B 是混合推理模型，支持 reasoning/non-reasoning、函数调用、结构化输出和长上下文。" },
      { title: "配置可复现", body: "用 hermes config get/set/check 管理普通设置；凭据留在 .env。记录模型 ID、Profile 与关键参数以便复现。" },
    ],
    checkpoints: ["区分四个配置层", "隔离 Profile", "保护密钥", "记录模型版本"],
    lab: { task: "为本地研究助手建立隔离配置。", input: "Provider 可选 Nous Portal、OpenRouter 或本地端点。", procedure: ["创建 research Profile", "选择模型并记录上下文需求", "把凭据写入 .env", "运行 hermes config check"], successCriteria: ["Profile 不是 default", "普通设置与凭据分离", "配置检查通过"] },
    practice: { type: "builder", prompt: "为“本地研究助手”选择 Provider 和隔离 Profile。", fields: [{ id: "provider", label: "模型来源", type: "select", options: ["Nous Portal", "OpenRouter", "本地端点"] }, { id: "profile", label: "Profile", type: "select", options: ["research", "default", "personal"] }], expected: { profile: "research" }, commandTemplate: ({ provider, profile }) => `hermes -p ${profile || "<profile>"} model  # ${provider || "<provider>"}`, success: "配置边界清晰：研究环境与默认环境相互隔离。", hint: "两个字段都要填写，研究任务应使用 research Profile。" },
    takeaways: ["模型能力与 Agent 身份分层", "Profile 是隔离单元"], troubleshooting: "模型不可用时先用 hermes model 切回已知可用模型，不要同时修改 Profile、Provider 和工具配置。",
    references: [{ label: "Configuring Models", url: "https://hermes-agent.nousresearch.com/docs/user-guide/configuring-models" }, { label: "Hermes 4.3 model card", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B" }],
  },
  {
    id: "prompt-contracts", number: "04", phaseId: "reliable", level: "Beginner", title: "Prompt 契约", shortTitle: "把需求写成可验收的契约",
    summary: "用目标、上下文、边界、输出结构和成功标准构造稳定 Prompt，并练习 JSON Schema 结构化输出。",
    objective: "把模糊请求改写成可验证 Prompt，并判断何时使用 reasoning 与结构化输出。",
    prerequisites: ["理解 Agent Loop", "能够描述任务输入与输出"],
    preQuiz: { prompt: "哪个字段最能减少“看起来完成但无法验收”？", options: [option("criteria", "成功标准", "明确完成证据"), option("tone", "语气", "只影响表达"), option("length", "字数", "不是正确性的充分条件")], correct: "criteria", explanation: "成功标准把主观完成转化为可检查证据。" },
    command: "hermes chat --prompt '<task contract>'",
    trace: ["声明目标与输入", "限定工具和边界", "定义输出 Schema", "按成功标准自检"],
    steps: [
      { title: "五段式任务契约", body: "写清目标、已知上下文、允许范围、输出格式和成功标准。先约束事实与边界，再调整语气。" },
      { title: "结构化输出", body: "对下游程序使用 JSON Schema，明确 required 字段、枚举和禁止额外字段；不要靠解析自然语言猜测状态。" },
      { title: "选择推理模式", body: "复杂规划与约束冲突适合 reasoning；简单抽取和格式转换可用 non-reasoning，以降低延迟与无关展开。" },
      { title: "把失败变成输入", body: "把验证错误、缺失字段和工具输出反馈给下一轮，并限制修复范围。不要只重复原 Prompt。" },
    ],
    checkpoints: ["写出任务目标", "限定作用域", "定义输出结构", "列出成功标准"],
    lab: { task: "设计一个仓库健康报告 Prompt。", input: "仓库路径、允许的只读工具、期望 JSON 字段。", procedure: ["列出目标和非目标", "定义 findings/risks/tests 字段", "要求引用文件路径", "用一条缺字段样例测试修复回合"], successCriteria: ["输出可通过 JSON 校验", "每条发现包含证据", "未请求写入或联网"] },
    practice: { type: "multi", prompt: "选择一个可靠任务契约必须包含的四项。", options: [option("goal", "明确目标", "说明最终要得到什么"), option("context", "输入与上下文", "提供必要事实"), option("boundary", "工具与边界", "限制副作用"), option("criteria", "成功标准", "定义验收证据"), option("flattery", "礼貌夸赞", "不影响可验证性")], correct: ["goal", "context", "boundary", "criteria"], success: "任务契约完整，Hermes 可以据此执行并自检。", hint: "选择能约束目标、输入、执行和验收的内容。" },
    takeaways: ["Prompt 是任务契约", "结构化输出服务于下游验证"], troubleshooting: "JSON 经常不合法时，缩小 Schema、给一个合法示例，并要求失败时只返回 validation_errors。",
    references: [{ label: "Hermes 4.3 structured outputs", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B" }, { label: "CLI", url: "https://hermes-agent.nousresearch.com/docs/user-guide/cli" }],
  },
  {
    id: "tools-context", number: "05", phaseId: "reliable", level: "Intermediate", title: "工具、Context 与审批", shortTitle: "组合最小且可审计的工具链",
    summary: "从任务反推 Toolset，使用 Context Files 固化项目约定，并让高风险操作经过明确审批。",
    objective: "为代码库任务选择最小工具集，区分上下文指令与长期记忆，并设置写入门。",
    prerequisites: ["能够写任务契约", "理解本地文件副作用"],
    preQuiz: { prompt: "项目编码规范最适合放在哪一层？", options: [option("context", "项目 Context File", "随项目版本控制并按目录生效"), option("memory", "全局 Memory", "可能污染其他项目"), option("prompt", "每次手写", "容易遗漏")], correct: "context", explanation: "稳定项目约定应进入项目上下文文件并随代码审查。" },
    command: "hermes tools",
    trace: ["读取项目 Context", "启用最小 Toolset", "先只读形成计划", "写入前请求审批"],
    steps: [
      { title: "工具越少越清晰", body: "每增加一种工具都会增加选择成本与攻击面。先从 File 和 Terminal 的只读用法开始，再按任务增加 Browser 或代码执行。" },
      { title: "Context Files 管项目规则", body: "把目录结构、构建命令和代码规范作为版本化上下文；不要把 API 密钥、临时任务或个人隐私写进去。" },
      { title: "读写分阶段", body: "先只读盘点并输出计划，再开放目标文件的写入。审批应说明工具、路径、次数和预期变化。" },
      { title: "验证工具结果", body: "要求引用读取过的文件、实际命令和退出状态，并用测试或 diff 证明结果符合任务契约。" },
    ],
    checkpoints: ["读取 Context", "限制 Toolset", "分离读写阶段", "验证工具证据"],
    lab: { task: "扫描仓库并生成 README 草稿。", input: "一个已有源码但无 README 的练习仓库。", procedure: ["读取项目 Context", "用 File/Terminal 只读搜索", "输出 README 结构计划", "仅批准写入 README.draft.md"], successCriteria: ["未启用无关 Browser/Image 工具", "草稿引用真实脚本", "没有覆盖已有文件"] },
    practice: { type: "multi", prompt: "选择完成“扫描当前仓库并生成 README 草稿”的最小能力集合。", options: [option("terminal", "Terminal", "列目录并搜索"), option("file", "File", "读取并写草稿"), option("approval", "Write approval", "写入前暂停"), option("browser", "Browser", "控制网页"), option("image", "Image generation", "生成视觉资产")], correct: ["terminal", "file", "approval"], success: "工具链足够完成任务，写入仍处于你的控制。", hint: "任务不需要访问网页或生成图片。" },
    takeaways: ["项目规则进入 Context", "工具按任务最小化"], troubleshooting: "若 Agent 忽略 Context，检查文件位置与作用域，并在 Prompt 中要求先复述适用规则再执行。",
    references: [{ label: "Tools", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools" }, { label: "Context Files", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/context-files" }],
  },
  {
    id: "sessions-memory", number: "06", phaseId: "reliable", level: "Intermediate", title: "Session、Memory 与 SOUL", shortTitle: "让上下文分层而不过度记忆",
    summary: "区分原始会话、压缩经验、稳定用户信息、人格原则与 Profile 隔离，设计可审查的记忆写入。",
    objective: "把不同信息放入正确层级，并通过 Memory gate 避免短期或敏感信息长期化。",
    prerequisites: ["使用过至少两个 Session", "了解 Profile"],
    preQuiz: { prompt: "要找回上周调试的完整报错，应先查哪里？", options: [option("session", "Session search", "保留原始交互与工具上下文"), option("memory", "Agent Memory", "是压缩后的经验"), option("soul", "SOUL.md", "只描述原则")], correct: "session", explanation: "原始历史用会话搜索，复用结论才进入 Memory。" },
    command: "hermes sessions list",
    trace: ["搜索原始 Session", "提取可复用结论", "审查长期价值与敏感性", "经 Memory gate 写入"],
    steps: [
      { title: "Session 保存事实", body: "Session 是原始交互记录，适合找回命令、报错和当时上下文；不要把全部历史塞回当前 Prompt。" },
      { title: "Memory 保存经验", body: "Memory 适合可复用流程、项目约定和失败结论；临时状态、一次性需求和秘密不应长期保存。" },
      { title: "SOUL 定原则", body: "SOUL.md 描述长期行为风格与价值边界，不是知识库、配置文件或任务清单。" },
      { title: "写入要可审查", body: "长期记忆会改变后续行为。启用审批并记录来源、适用范围、更新时间和删除条件。" },
    ],
    checkpoints: ["检索 Session", "提炼 Memory", "区分 SOUL", "审批长期写入"],
    lab: { task: "整理一次失败调试并决定哪些内容长期保存。", input: "完整报错、三条尝试命令、最终根因和个人访问令牌。", procedure: ["用 Session 保留原始记录", "提炼根因与通用修复", "排除令牌和临时路径", "批准一条带来源的 Memory"], successCriteria: ["Memory 不含秘密", "保留可复用根因", "能够从 Session 找回原始证据"] },
    practice: { type: "choice", prompt: "“某依赖在 Node 22 下失败，固定到 Node 20 可恢复”最适合保存在哪里？", options: [option("memory", "项目 Agent Memory", "可复用的项目经验"), option("soul", "SOUL.md", "人格原则"), option("user", "User profile", "个人稳定偏好"), option("none", "完全不保存", "会丢失复用价值")], correct: "memory", success: "正确。这是可复用的项目排错经验。", hint: "它不是人格或个人身份事实。" },
    takeaways: ["Session 是记录，Memory 是提炼", "长期写入必须可审查"], troubleshooting: "发现错误 Memory 时立即删除或修订，并在当前会话显式声明不再使用旧结论。",
    references: [{ label: "Sessions", url: "https://hermes-agent.nousresearch.com/docs/user-guide/sessions" }, { label: "Memory", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/memory" }, { label: "Profiles", url: "https://hermes-agent.nousresearch.com/docs/user-guide/profiles" }],
  },
  {
    id: "skills-plugins-mcp", number: "07", phaseId: "extensions", level: "Intermediate", title: "Skills、Plugins 与 MCP", shortTitle: "分清知识、扩展包与外部能力",
    summary: "用 Skills 渐进披露操作知识，用 Plugins 打包扩展，用 MCP 连接外部工具，并在安装前审查权限。",
    objective: "为一个真实任务选择正确扩展机制，安装并验证一项最小能力。",
    prerequisites: ["理解 Toolset", "能够审查配置和来源"],
    preQuiz: { prompt: "团队操作规范应优先实现为什么？", options: [option("skill", "Skill", "告诉 Agent 何时和如何做"), option("mcp", "MCP", "提供外部工具能力"), option("model", "新模型", "成本过高且不解决流程规范")], correct: "skill", explanation: "Skill 承载可审查的过程知识；MCP 负责工具协议。" },
    command: "hermes skills browse",
    trace: ["匹配 Skill 描述", "按需读取 SKILL.md", "发现 Plugin/MCP 工具", "用白名单限制暴露"],
    steps: [
      { title: "Skill 教怎么做", body: "Skill 用触发条件、Procedure、陷阱和 Verification 固化操作知识，并只在匹配任务时加载完整内容。" },
      { title: "Plugin 打包扩展", body: "Plugin 可以组合技能、工具或集成，适合可安装分发；仍需核对来源、依赖、版本和副作用。" },
      { title: "MCP 提供新能力", body: "MCP 通过 stdio 或 HTTP 暴露外部工具。它提供能力，不自动包含团队规则，也不自动代表安全。" },
      { title: "安装后做冒烟测试", body: "先列出暴露的工具，只启用必要项，用无副作用请求验证，再测试审批与错误路径。" },
    ],
    checkpoints: ["区分三类扩展", "审查来源", "限制工具白名单", "完成冒烟测试"],
    lab: { task: "安装并验收一个 Kubernetes Skill。", input: "Skills Hub 上的候选 Skill 与一个只读集群任务。", procedure: ["browse/search 候选", "审查 SKILL.md 和依赖", "安装到隔离 Profile", "用只读任务验证触发与输出"], successCriteria: ["Skill 来源可追溯", "没有开放无关 MCP 工具", "验证章节产生可检查证据"] },
    practice: { type: "multi", prompt: "选择一份可执行 SKILL.md 的四个关键部分。", options: [option("frontmatter", "Frontmatter", "名称与触发描述"), option("when", "When to Use", "适用边界"), option("procedure", "Procedure", "可操作步骤"), option("verification", "Verification", "完成证据"), option("slogan", "宣传口号", "不约束执行")], correct: ["frontmatter", "when", "procedure", "verification"], success: "结构完整：何时用、如何做、怎样证明都已明确。", hint: "选择能约束触发、执行和验收的内容。" },
    takeaways: ["Skill 是知识，MCP 是能力", "安装不等于可信"], troubleshooting: "Skill 未触发时先检查描述是否明确；MCP 无工具时检查启动命令、环境变量与工具白名单。",
    references: [{ label: "Skills", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/skills" }, { label: "MCP", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/mcp" }, { label: "Plugins", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/plugins" }],
  },
  {
    id: "automation", number: "08", phaseId: "extensions", level: "Intermediate", title: "Gateway、Cron、Hooks 与 Batch", shortTitle: "把一次成功变成可靠自动化",
    summary: "区分消息入口、定时触发、事件钩子和批处理，设计可追踪、可重试、有交付证据的自动化。",
    objective: "从触发、任务、工作目录到交付目标构建一个可观测的工作日早报。",
    prerequisites: ["基础聊天稳定", "已理解 Skills 与审批"],
    preQuiz: { prompt: "定时触发成功是否等于结果送达？", options: [option("no", "不等于", "执行与 Delivery 是不同状态"), option("yes", "等于", "忽略了运行或发送失败")], correct: "no", explanation: "自动化至少要区分调度、执行、验证和交付状态。" },
    command: "hermes gateway status",
    trace: ["Gateway 接收或保持连接", "Cron/Hook/Batch 触发", "Agent 执行并验证", "结果路由并记录状态"],
    steps: [
      { title: "选择正确触发器", body: "Gateway 是消息入口，Cron 处理时间计划，Hook 响应事件，Batch 处理成组输入。不要用定时轮询替代明确事件。" },
      { title: "自动化任务要自包含", body: "保存 schedule/trigger、prompt、Profile、工作目录、Skills、超时和 delivery，避免依赖某次交互里的隐含上下文。" },
      { title: "保留幂等性", body: "任务重试不能重复发消息或覆盖数据。为输出加入日期/任务 ID，并在写入前检查是否已经完成。" },
      { title: "交付必须可追踪", body: "记录触发、运行、验证、发送四种状态和失败原因，给人工提供重跑与停用路径。" },
    ],
    checkpoints: ["选择触发机制", "任务自包含", "设计幂等性", "追踪交付状态"],
    lab: { task: "创建工作日项目早报。", input: "工作日 09:00、项目目录、状态汇总 Prompt、Telegram 目标。", procedure: ["先在普通聊天中跑通 Prompt", "创建 Cron 并固定 Profile/目录", "配置 Telegram delivery", "模拟失败并查看历史"], successCriteria: ["同一天重跑不重复发送", "失败记录可查询", "停用和手动重跑路径明确"] },
    practice: { type: "builder", prompt: "构建工作日 09:00 的项目早报，并发送到 Telegram。", fields: [{ id: "schedule", label: "Schedule", type: "select", options: ["weekdays at 09:00", "every 5m", "daily at 23:00"] }, { id: "delivery", label: "Delivery", type: "select", options: ["Telegram", "CLI only", "Discord"] }, { id: "task", label: "Task", type: "text", placeholder: "汇总状态、阻塞项和今日计划" }], expected: { schedule: "weekdays at 09:00", delivery: "Telegram" }, commandTemplate: ({ schedule, delivery, task }) => `hermes cron create "${schedule || "<schedule>"}" "${task || "<task>"}"  # ${delivery || "<target>"}`, success: "自动化具备明确时间、任务和交付目标。", hint: "题目指定工作日 09:00 与 Telegram，Task 也不能为空。" },
    takeaways: ["触发、执行、交付是不同状态", "先手动跑通再自动化"], troubleshooting: "任务未送达时先查 gateway status 与 Cron 历史，区分未触发、执行失败和 delivery 失败。",
    references: [{ label: "Cron", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/cron" }, { label: "Batch Processing", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/batch-processing" }, { label: "Hooks", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/hooks" }],
  },
  {
    id: "delegation-routing", number: "09", phaseId: "extensions", level: "Intermediate", title: "委派与 Provider Routing", shortTitle: "拆分独立任务并匹配模型",
    summary: "把独立子任务交给隔离 Agent，并根据复杂度、延迟和成本选择 Provider，而由主 Agent 统一验收。",
    objective: "识别可并行任务，写出自包含委派说明，并为任务选择合理路由策略。",
    prerequisites: ["理解 Profile 隔离", "能够写成功标准"],
    preQuiz: { prompt: "什么任务最适合并行委派？", options: [option("independent", "输入和写入相互独立", "可以并行后统一汇总"), option("samefile", "同时改同一文件", "冲突风险高"), option("unknown", "目标仍然模糊", "子任务无法自包含")], correct: "independent", explanation: "并行的前提是依赖和写入边界清楚。" },
    command: "/agents",
    trace: ["拆分独立任务", "补全上下文与返回格式", "按成本/能力路由", "主 Agent 汇总验证"],
    steps: [
      { title: "并行需要独立性", body: "研究、测试归类和文档核对可并行；共享可变状态、强顺序依赖或同文件写入不适合并发。" },
      { title: "任务必须自包含", body: "给出目标、输入、约束、文件范围、允许的副作用和返回格式，避免“那个错误”之类的隐含指代。" },
      { title: "路由匹配任务", body: "高复杂推理使用强模型，批量抽取可选低延迟模型，敏感数据可走本地端点；设置可用 Provider 的回退边界。" },
      { title: "主 Agent 负责收口", body: "委派结果是证据输入，不是最终事实。主 Agent 仍要消解冲突、运行集成验证并报告剩余风险。" },
    ],
    checkpoints: ["判断独立性", "写自包含任务", "选择模型路由", "集中验收"],
    lab: { task: "设计发布前并行检查。", input: "依赖安全公告、测试输出、文档链接和一个共享源码文件。", procedure: ["拆出三个只读子任务", "分别定义输出 Schema", "为批量检查选择低成本模型", "由主 Agent 汇总并复核高风险项"], successCriteria: ["没有并行写同一文件", "每项结果含证据", "最终报告处理冲突"] },
    practice: { type: "multi", prompt: "选择可并行委派的三条独立工作流。", options: [option("research", "依赖安全公告", "只读外部研究"), option("tests", "测试失败归类", "分析既有输出"), option("docs", "文档链接核对", "检查链接与示例"), option("samea", "修改 App.jsx 上半段", "写共享文件"), option("sameb", "修改 App.jsx 下半段", "写同一文件")], correct: ["research", "tests", "docs"], success: "拆分合理：输入和写入边界独立，可并行后统一汇总。", hint: "避免两个子任务同时写同一个文件。" },
    takeaways: ["并行来自独立边界", "模型路由服从任务约束"], troubleshooting: "结果冲突时不要多数表决；回到各自证据、版本和假设，由主 Agent 重新验证。",
    references: [{ label: "Delegation", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/delegation" }, { label: "Provider Routing", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/provider-routing" }],
  },
  {
    id: "sandbox-security", number: "10", phaseId: "production", level: "Advanced", title: "Sandbox、Egress 与 ACP", shortTitle: "把代码执行放进明确边界",
    summary: "比较 local、Docker 与 SSH 后端，使用 Egress Proxy 限制网络，并通过 ACP 把 Hermes 接入编辑器协议。",
    objective: "为不可信仓库选择隔离后端、网络策略和恢复点，并验证边界确实生效。",
    prerequisites: ["理解工具审批", "具备 Docker 或 SSH 基础"],
    preQuiz: { prompt: "运行陌生仓库安装脚本时，首选哪种后端？", options: [option("docker", "Docker Sandbox", "隔离文件系统和进程"), option("local", "Local", "直接影响主机"), option("gateway", "Gateway", "不是执行隔离后端")], correct: "docker", explanation: "Docker 是陌生代码的合理起点，仍需额外限制挂载和网络。" },
    command: "hermes config set terminal.backend docker",
    trace: ["选择执行后端", "限制挂载与凭据", "启用 Egress 策略", "验证阻断与恢复"],
    steps: [
      { title: "后端按信任选择", body: "local 适合受信环境；docker 提供本机隔离；ssh 用于受控远端。Modal、Daytona、Vercel Sandbox 等适合弹性工作负载。" },
      { title: "隔离不只是一条命令", body: "限制挂载目录、用户权限、环境变量、资源和生命周期。不要把主机凭据或 Docker socket 默认映射进去。" },
      { title: "网络默认收紧", body: "使用 Egress Proxy 控制允许访问的域名和协议，并测试被禁止请求确实失败。网络白名单应服务于明确任务。" },
      { title: "ACP 是集成边界", body: "hermes acp 让兼容客户端通过 Agent Client Protocol 连接 Hermes；仍应保持 Profile、工具和审批策略一致。" },
    ],
    checkpoints: ["选择 Sandbox", "限制挂载与秘密", "验证 Egress", "理解 ACP 边界"],
    lab: { task: "在隔离环境审查陌生 Node 仓库。", input: "只读源码、允许 npm registry、禁止其他外网。", procedure: ["切换 terminal.backend=docker", "只挂载练习目录", "配置并启动 Egress", "运行依赖审计并测试禁止域名"], successCriteria: ["主机目录未暴露", "仅 npm registry 可访问", "退出后容器状态可清理"] },
    practice: { type: "multi", prompt: "选择运行陌生代码前必须具备的四项控制。", options: [option("backend", "隔离执行后端", "Docker 或受控 SSH"), option("mount", "最小目录挂载", "只暴露任务输入"), option("egress", "网络白名单", "限制外连"), option("secret", "不注入无关凭据", "降低泄漏风险"), option("root", "永久 root 权限", "扩大破坏面")], correct: ["backend", "mount", "egress", "secret"], success: "隔离边界完整：执行、文件、网络和秘密都已收紧。", hint: "选择减少陌生代码权限的四项。" },
    takeaways: ["Sandbox 与 Egress 是两条边界", "隔离必须通过负向测试验证"], troubleshooting: "Docker 后端失败时检查 daemon、镜像和挂载；Egress 误拦截时只添加所需域名，不要临时全开放。",
    references: [{ label: "Security", url: "https://hermes-agent.nousresearch.com/docs/user-guide/security" }, { label: "Docker", url: "https://hermes-agent.nousresearch.com/docs/user-guide/docker" }, { label: "ACP", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/acp" }],
  },
  {
    id: "inference-tuning", number: "11", phaseId: "production", level: "Advanced", title: "推理、量化与微调", shortTitle: "从 Prompt 到 LoRA 与 RL 的决策阶梯",
    summary: "用 Transformers、vLLM、SGLang 与本地量化运行 Hermes 4.3，并按成本从 Prompt、Skill、SFT/LoRA 走向 Atropos RL。",
    objective: "选择合适推理方案和采样参数，并判断问题是否真的需要微调。",
    prerequisites: ["理解 Prompt 与 Skills", "了解 GPU/显存基本概念"],
    preQuiz: { prompt: "团队流程经常被遗漏时，第一步通常是什么？", options: [option("skill", "改 Prompt 或 Skill", "成本低且可快速评测"), option("rl", "直接做 RL", "成本高且需要环境与指标"), option("405b", "换最大模型", "不一定解决流程缺失")], correct: "skill", explanation: "先用最便宜、可逆的层解决；有稳定数据和指标后才微调。" },
    command: "python -m vllm.entrypoints.openai.api_server --model NousResearch/Hermes-4.3-36B --tool-call-parser hermes",
    trace: ["定义评测集", "选择 Serving/量化", "调 Prompt 与 Skill", "必要时 SFT/LoRA 或 RL"],
    steps: [
      { title: "使用官方 Chat Template", body: "通过 tokenizer.apply_chat_template 构造角色头；推理模式使用 thinking=True。不要手拼可能随版本变化的特殊 token。" },
      { title: "选择 Serving", body: "Transformers 适合实验，vLLM/SGLang 适合服务，GGUF + llama.cpp/Ollama/LM Studio 适合本地量化。工具解析器要与服务框架匹配。" },
      { title: "从可逆层开始", body: "决策阶梯是 Prompt → Skill → SFT/LoRA → RL。只有当错误稳定、数据充足、评测明确且提示层无法解决时才升级。" },
      { title: "评测驱动参数", body: "模型卡建议 temperature=0.6、top_p=0.95、top_k=20 作为起点；最终参数必须通过目标任务评测，而非照抄。" },
    ],
    checkpoints: ["使用 Chat Template", "选择 Serving", "判断是否微调", "用评测选参数"],
    lab: { task: "设计 Hermes 4.3 结构化工具调用实验。", input: "一个天气工具 Schema、20 条提示和合法 JSON 判定器。", procedure: ["加载官方 Chat Template", "分别运行 reasoning/non-reasoning", "记录 JSON 与工具选择正确率", "只在有系统性差距时提出 LoRA 计划"], successCriteria: ["20 条样例可重复", "报告延迟与正确率", "微调决策有数据依据"] },
    practice: { type: "choice", prompt: "模型已能理解任务，但总忘记团队特有的发布清单。最合适的下一步是什么？", options: [option("skill", "编写并评测发布 Skill", "显式固化流程知识"), option("lora", "立即训练 LoRA", "成本更高"), option("rl", "立即搭建 RL", "尚无必要"), option("bigger", "只换更大模型", "不能保证遵循团队流程")], correct: "skill", success: "正确。先用可审查、可快速迭代的 Skill 解决流程知识。", hint: "遵循从低成本、可逆方案开始的阶梯。" },
    takeaways: ["Serving 与模型格式要匹配", "微调前先有稳定评测"], troubleshooting: "工具调用无法解析时，核对 Chat Template、tool parser 与服务框架；不要先调整采样参数掩盖格式问题。",
    references: [{ label: "Hermes 4.3 model card", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B" }, { label: "Atropos", url: "https://github.com/NousResearch/atropos" }],
  },
  {
    id: "capstone", number: "12", phaseId: "production", level: "Advanced", title: "评测驱动毕业项目", shortTitle: "把 Hermes 工作流交付到生产边界",
    summary: "综合 Prompt、Tools、Memory、Automation、Delegation、Sandbox 与评测，设计一个可审计、可恢复的 PR 审查助手。",
    objective: "交付一个有基线、评测集、权限边界、失败策略与运行证据的完整工作流设计。",
    prerequisites: ["完成前三阶段", "掌握基本 Git 与测试"],
    preQuiz: { prompt: "生产化前最先需要哪项证据？", options: [option("baseline", "可重复评测基线", "知道当前表现与退化"), option("demo", "一次成功演示", "不能代表稳定性"), option("autonomy", "永久跳过审批", "扩大风险")], correct: "baseline", explanation: "没有基线就无法判断改动是否真正提升可靠性。" },
    command: "hermes checkpoints list",
    trace: ["限定仓库与分支", "运行离线评测", "审批后执行", "保留 Checkpoint 与报告"],
    steps: [
      { title: "先定义风险预算", body: "明确可读仓库、允许分支、可写文件、外部消息目标、人工审批点和不可接受失败。" },
      { title: "建立评测集", body: "覆盖正常、边界、恶意 Prompt、工具失败和恢复场景；记录正确率、误报、成本、延迟与人工接管率。" },
      { title: "设计失败策略", body: "超时、Provider 故障、测试失败或权限不足时应停止、降级或请求人工，不得静默跳过。" },
      { title: "用证据完成交付", body: "最终报告包含配置版本、实际变更、评测结果、Checkpoint、回滚步骤和仍需人工判断的风险。" },
    ],
    checkpoints: ["限定作用域", "建立评测基线", "验证失败策略", "提供回滚证据"],
    lab: { task: "设计并评审一个定时 PR 审查 Agent。", input: "只读代码、可写审查草稿、Slack 交付、30 条测试任务。", procedure: ["定义权限矩阵", "建立基线并记录指标", "在 Sandbox 运行失败注入", "审批后发送一条测试交付", "生成运行手册与回滚说明"], successCriteria: ["高风险动作需审批", "评测覆盖失败路径", "每次运行有 Checkpoint/日志", "报告暴露剩余风险"] },
    practice: { type: "multi", prompt: "上线 PR 审查 Agent 前必须具备哪些控制？", options: [option("scope", "仓库与分支白名单", "限制目标"), option("approval", "写入与发送审批", "控制副作用"), option("rollback", "Checkpoint / Git 恢复点", "支持恢复"), option("evaluation", "测试集与运行证据", "证明表现"), option("yolo", "永久跳过确认", "提高风险")], correct: ["scope", "approval", "rollback", "evaluation"], success: "毕业挑战完成：能力已经进入可审查、可恢复、可度量的运行边界。", hint: "选择作用域、审批、恢复和评测四类控制。" },
    takeaways: ["生产化以评测和风险预算为起点", "自动化必须保留人工接管"], troubleshooting: "指标退化时先回滚配置/Skill/模型版本，再复现失败样例；不要在生产任务上直接试错。",
    references: [{ label: "Checkpoints", url: "https://hermes-agent.nousresearch.com/docs/user-guide/checkpoints-and-rollback" }, { label: "Learning Path", url: "https://hermes-agent.nousresearch.com/docs/getting-started/learning-path" }, { label: "Self Evolution", url: "https://github.com/NousResearch/hermes-agent-self-evolution" }],
  },
];

export const repositories = [
  { name: "NousResearch/hermes-agent", role: "官方核心", language: "Python + TypeScript", url: "https://github.com/NousResearch/hermes-agent", idea: "把模型、工具运行时、持久记忆、Skills、消息网关与自动化组合成可扩展 Agent harness。", design: "Provider 可替换、界面与核心解耦、能力按需披露、会话与长期记忆分层、副作用显式治理。", features: ["TUI / CLI / Desktop", "Memory / Sessions", "Skills / MCP / Plugins", "Cron / Gateway / Delegation"] },
  { name: "microsoft/AI-For-Beginners", role: "教学体系参考", language: "Markdown + Jupyter", url: "https://github.com/microsoft/AI-For-Beginners", idea: "用环境准备、课前测验、理论、可执行实验、课后测验与延伸阅读形成低门槛学习闭环。", design: "按周递进、项目驱动、频繁低风险反馈，每个实验明确任务、输入、执行步骤和期望结果。", features: ["课程 Setup", "Pre/Post Quiz", "Notebook / Code Challenge", "Assignment / Self-study"] },
  { name: "NousResearch/Hermes-4.3-36B", role: "官方模型资料", language: "Transformers", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B", idea: "36B 混合推理模型，面向工具调用、结构化输出、长上下文和通用对话。", design: "Reasoning 与 non-reasoning 模式并存，使用 Chat Template 和显式工具调用标记适配多种 Serving。", features: ["Function calling", "JSON Schema", "Hybrid reasoning", "vLLM / SGLang / GGUF"] },
  { name: "NousResearch/hermes-agent-self-evolution", role: "官方实验项目", language: "Python", url: "https://github.com/NousResearch/hermes-agent-self-evolution", idea: "用 DSPy + GEPA 对 Skills、提示与代码进行基于评测的迭代优化。", design: "把自我改进变成候选生成、评测、比较与保留优胜版本的闭环。", features: ["GEPA 优化", "Skill 演化", "可度量评测", "实验追踪"] },
  { name: "NousResearch/atropos", role: "官方 RL 工具链", language: "Python", url: "https://github.com/NousResearch/atropos", idea: "为 Agent 和语言模型训练构建可复现的强化学习环境与 rollout 工作流。", design: "用显式环境、奖励与评测把行为优化建立在可测任务上。", features: ["RL environments", "Rollouts", "Reward design", "Training workflows"] },
  { name: "fathah/hermes-desktop", role: "社区桌面端", language: "TypeScript", url: "https://github.com/fathah/hermes-desktop", idea: "用原生桌面工作台降低安装、Provider 配置和日常管理门槛。", design: "围绕会话、Profile、Memory、Skills、Schedules 与 Gateway 组织 GUI。", features: ["引导式安装", "流式工具进度", "Profile / Memory", "Schedules / Messaging"] },
  { name: "0xNyk/awesome-hermes-agent", role: "社区资源索引", language: "Markdown", url: "https://github.com/0xNyk/awesome-hermes-agent", idea: "聚合 Surfaces、Skills、Plugins、Memory Providers 与 Guides。", design: "通过类别和成熟度帮助学习者发现生态，同时保留来源审查责任。", features: ["Skills", "Plugins", "Memory providers", "Guides"] },
  { name: "alchaincyf/hermes-agent-orange-book", role: "中文学习资料", language: "PDF / Markdown", url: "https://github.com/alchaincyf/hermes-agent-orange-book", idea: "从自改进、记忆、工具、多 Agent、安全与部署建立中文整体视角。", design: "概念解释配合界面和架构分析，补充官方文档之外的学习路径。", features: ["中文指南", "记忆分析", "多 Agent", "安全边界"] },
];

export const architectureLayers = [
  { title: "Curriculum", detail: "13 课、4 阶段课程数据，包含多端安装、先修、诊断、概念、模拟练习、实验、课后检查与来源。" },
  { title: "Learning Engine", detail: "诊断判定、练习反馈、课程完成、阶段进度与掌握度保持为前端状态机。" },
  { title: "Persistence", detail: "localStorage v2 保存完成课程、诊断结果与最近位置，并迁移 v1 数据。" },
  { title: "Safety Shell", detail: "React + Vite 浏览器模拟，不读取本机 Hermes 配置、凭据或执行真实命令。" },
];
